name: Miro's blog
description: A blog on tech
meta_description: "Miro's blog, Blogging about tech"

markdown: kramdown
highlighter: rouge
logo: false
paginate: 15
baseurl: /kasper
domain_name: "http://yourblog-domain.com"
google_analytics: "UA-XXXXXXXX-X"
plugins: [jekyll-paginate]

# Details for the RSS feed generator
url: ""
author: "Miro"

# Disqus config
disqus-shortname: ""
